language: node_js
sudo: false
node_js:
- '8'
- '10'
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: npmjs@heise.de
  api_key:
    secure: mYbgKFrbWdlIqAHgfm6jd0RJVMK8pA2w2zBw30krAfgE7N3iKiauXbtko1sI4UM7pcNgprK5RiLw59VIXwjXS1l4Wzf//oHEwiAc5N7m/ZPQHrJHxGocq2cxMIzixhjQN6QfQFodsgf317B37ln7ej1Xx5YitF5Br8yZ0GJxmrtfj1Y+zKrsX4ZoteC2eUm9pryxTdJN6qhS3dk2b25/zYW2YTRjUZm2xybm7JOtzhaJHcQMLRH7+lsCvSDRZOedZgmUxtBt/m19gflyogNFw8GWJhN959OUs1aVQPQHjHjtfX2LAknlOX7QwUdcY6dniouf1jrfO809h+j5y+9yF+WmCHrY/5eqrIx57828drMq47k439e6YjYSHVpVryc4sS63ZbJ6mUkxX7EiRfLvQcKdkYYDUAmEvpvNXDSySeEps/5aSqAU00dU5soO+JZdWDPmI7cWlzVCBmTgB4iJAB90QaTJ2shmE46S4KhlKmfUWH6Nezldw9qq6p2o1VU7q+GNdbbeeHmT3D4QLxPKOemnDWbJio6ctXA1bPu1evtNMCrtQKo8eTYNCYyeTcNiHhjvE0qzwSzRn9+OyaWe4Omy16ybpmSLSaVYy0LCtAQf8c48afvKv2fzqg9p4aa+0AOUKB8lQj0U1DAM4lW/TByCBbJJn6Tl+D9G5jqFexQ=
  on:
    tags: true
    repo: heiseonline/embetty-base
    node_js: '8'
env:
  global:
    secure: ZJ2A+YqqLfcRmOYG6+36ZapATBi2sVRjvHr+o6rVHfFIz6ltQCam2HvPmaHjIEu5A/ha1kktMtFFzWXiz2MjaGGe2754Xcv91832Uq9F5bxnHimDM6EeCS6EMvWyqwuaRKTSFoSJA4S8QvCWkTEVr/LkUTdxwDAKa/VXtxi4/E2D9cz28tKMEUFh4EVRewB8XOmg38VjGuoy9QtuHF/iXAif4TsPu9wXCRvLtdW00dyRAsKj2myHPbuvZTW1w5hBi4u7B3TcwxmORxBrDHmppU8IioVpIHhHnR81RdSJkqjq6ehch3B4HpMeFt0XyJTedHjtFMN7Kn+n1y8tLcscbdazsS8GgzFpq6tWWfkGhI9hJ0hucwaXXm8HZudlaBIQaizEMScwYiq8kHq7P1dyKl24WFpTf9kJivU+j110s+oxpiRXRVaDcbyJ51c+RnqSzc3KMDtJX8zk/bN+J83wXdkOIBsHgehKQgb7PhMGAiiVtaxZt/h9bp0iMScXwd/MUlGA5XUizU46EE3BkU9meD110RJFUAHfCc64YIfTJmCoa6wpOIRQ0ZoTsWlWAMayHL/k0ZFQXDRY/rGuwk8NNFndniq+J0fsVhGVQhOYk4UXxwskutSJf2LUYa3lOVF/NHni7msYbuQFFYV06pB2NekrZu3Xj2Zsjc6JEX+bLec=
